---
# tasks file for mysql
- name: Specify MySQL root password before installing
  debconf: 
    name: 'mysql-server' 
    question: 'mysql-server/root_password' 
    value: '{{mysql_root_password | quote}}' 
    vtype: 'password'
  sudo: true
- name: Confirm MySQL root password before installing
  debconf: 
    name: 'mysql-server' 
    question: 'mysql-server/root_password_again' 
    value: '{{mysql_root_password | quote}}' 
    vtype: 'password'
  sudo: true
- name: Install MySQL
  apt: 
    name: '{{ item }}' 
    update_cache: yes 
    cache_valid_time: 3600 
    state: present
  sudo: yes
  with_items:
  - mysql-server
  - python3-pymysql
- name: Copy the root credentials as .my.cnf file
  template: 
    src: 'root.cnf.j2' 
    dest: '/root/.my.cnf'
    owner: root
    mode: 0600
  sudo: yes
- name: ensure mysql listening on all ports
  lineinfile: 
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
    regexp: '^bind-address'
    line: "bind-address = 0.0.0.0"
- name: Stop the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: stopped
- name: Start the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: started
    enabled: true
- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: create htok database
  mysql_db: 
    name: HTOK 
    state: present
    login_user: root 
    login_password: "{{ mysql_root_password }}"
- name: create htok_user user
  mysql_user: 
    name: htok_user 
    password: htok 
    priv: HTOK.*:ALL 
    host: '%' 
    state: present
    login_user: root 
    login_password: "{{ mysql_root_password }}"
- name: Restart the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: restarted